spring:
  application:
    name: register-eureka
  profiles:
    active: node1

eureka:
  client:
    service-url:
      defaultZone: http://${APPLICATION_HOST:node1}:30001/eureka/,http://${APPLICATION_HOST:node1}:30002/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: node1
    appname: ${spring.application.name}