
server:
  port: ${SERVER_PORT:9080}
  servlet:
    context-path: ${CONTEXT_PATH:/school-spider}

# spider config
spider:
  thread:
    amount: ${SPIDER_THREAD_AMOUNT:10}
    helpurl: ${SPIDER_THREAD_HELPURL:http://xuexiao.pinwaiyi.com/hy/list.php?fid=360}


spring:
  kafka:
    topic: klaus
#    consumer:
#      #group-id: test-demo
#      #key-deserializer: org.springframework.kafka.support.serializer.StringDeserializer
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
#      fetch-min-size: 20
#      fetch-max-wait: 6000
#      enable-auto-commit: true
#      max-poll-records: 100
#      auto-commit-interval: 10
#      auto-offset-reset: latest
#      properties:
#        spring.json.trusted.packages: com.klaus.interview.basespider.model
#        security:
#          protocol: SASL_PLAINTEXT
#        kerberos:
#          domain:
#            name: hadoop.hadoop.com
#
#        sasl:
#          kerberos:
#            service:
#              name: kafka
#    listener:
#      type: batch
#      ack-mode: batch
#      ack-time: 60
#      poll-timeout: 3000
#      #      client-id: com.klaus
#      concurrency: 1
#  #    admin:
#  #      properties:
    producer:
      bootstrap-servers: 192.168.43.235:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      batch-size: 10
      retries: 2
      acks: 0
