server:
  port: 9091
  servlet:
    context-path: /spring-redis
    application-display-name: ${spring.application.name:spring-redis-node1}
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 4
    jedis:
      pool:
        max-active: 80
        min-idle: 0
        max-idle: 80
        max-wait: -1ms
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/${MYSQL_DB:spring_interview}?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:admin123}
    hikari:
      auto-commit: true
      pool-name: ${spring.application.name}-pool
      connection-timeout: 30000
      maximum-pool-size: 1000
      minimum-idle: 10
      idle-timeout: 30000
      connection-test-query: select 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
#debug: true
#trace: true
