spring:
  application:
    name: spring-elasticsearch
  profiles:
    active: node1
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  # elastic search related config
  data:
    elasticsearch:
      cluster-name: local-elastic
      cluster-nodes: 192.168.43.235:9300
      repositories:
        enabled: true
#      properties:
  # kafka config
  kafka:
    consumer:
      bootstrap-servers: 192.168.43.235:9092
      group-id: elastic-school-consumer-new
      #key-deserializer: org.springframework.kafka.support.serializer.StringDeserializer
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      fetch-min-size: 20
      fetch-max-wait: 600
      max-poll-records: 100
      auto-offset-reset: latest
      auto-commit-interval: 10
      enable-auto-commit: true
      properties:
        spring.json.trusted.packages: com.klaus.interview.basespider.model
    listener:
      type: batch
      ack-mode: batch
      ack-time: 60
      poll-timeout: 3000
      concurrency: 1

swagger:
  enabled: true
  title: ${spring.application.name}
  description: ES搜索最佳实践
  version: 1.0.0
  license:
  licenseUrl:
  termsOfServiceUrl:
  contact:
    name: ${AUTHOR_NAME:klaus}
    url:
    email: ${AUTHOR_EMAIL:niklausjulie@gmail.com}
  base-package: com.klaus.interview.springelasticsearch.controller
  # 公共参数，鉴权token
#  authorization:
#    key-name: Authorization
#  global-operation-parameters[0]:
#    name: Authorization
#    description: 鉴权token
#    modelRef: string
#    parameterType: header
#    # 公共参数写成requierd, 对于不需要登录的接口随便写一个字符串即可
#    required: false
debug: false
